# train and val datasets (image directory or *.txt file with image paths)

train: data/UCAS_AOD/yolo_train/images/
test: data/UCAS_AOD/yolo_test/images/

# number of classes
nc: 2

# class names
names: [ 'car', 'airplane']
