# train and val datasets (image directory or *.txt file with image paths)

train: data/DOTA/yolo_trainval/images/
test: data/DOTA/yolo_test/images/

# number of classes
nc: 15

# class names
names: [ 'plane', 'baseball-diamond', 'bridge', 'ground-track-field', 'small-vehicle', 'large-vehicle', 'ship', 'tennis-court', 'basketball-court', 'storage-tank',  'soccer-ball-field', 'roundabout', 'harbor', 'swimming-pool', 'helicopter']
